name: Cl

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: macos-12

    steps:
    - name: Download ngrok
      run: curl -fsSL https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-darwin-amd64.zip -o ngrok.zip
    - name: Extract ngrok
      run: unzip ngrok.zip
    - name: Auth (using encrypted secret)
      run: ./ngrok authtoken ${{ secrets.NGROK_AUTH_TOKEN }}
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
    - name: Create new admin user
      run: |
        sudo dscl . -create /Users/newadmin
        sudo dscl . -create /Users/newadmin UserShell /bin/bash
        sudo dscl . -create /Users/newadmin RealName "New Admin"
        sudo dscl . -create /Users/newadmin UniqueID "1010"
        sudo dscl . -create /Users/newadmin PrimaryGroupID 80
        sudo dscl . -create /Users/newadmin NFSHomeDirectory /Users/newadmin
        sudo dscl . -passwd /Users/newadmin P@ssw0rd!
        sudo dscl . -append /Groups/admin GroupMembership newadmin
    - name: Change runner password using pwpolicy
      run: |
        sudo dscl . -passwd /Users/newadmin P@ssw0rd!
        sudo dscl . -merge /Users/runner authentication_authority ";ShadowHash;"
        sudo dscl . -merge /Users/runner passwd "XXXXXXXXXXXX"
        sudo pwpolicy -u runner -setpolicy "newPassword=P@ssw0rd! minChars=8 requiresMixedCase=1 requiresAlpha=1 requiresNumeric=1"
    - name: Enable Screen Sharing
      run: |
        sudo /System/Library/CoreServices/RemoteManagement/ARDAgent.app/Contents/Resources/kickstart -activate -configure -access -on -privs -all -restart -agent -menu
        sudo /System/Library/CoreServices/RemoteManagement/ARDAgent.app/Contents/Resources/kickstart -configure -users runner -access -on -privs -all
    - name: Set VNC password
      run: |
        echo "P@ssw0rd!" | sudo tee /Library/Preferences/com.apple.VNCSettings.txt
        sudo /System/Library/CoreServices/RemoteManagement/ARDAgent.app/Contents/Resources/kickstart -configure -clientopts -setvnclegacy -vnclegacy yes
        sudo /System/Library/CoreServices/RemoteManagement/ARDAgent.app/Contents/Resources/kickstart -configure -clientopts -setvncpw -vncpw P@ssw0rd!
    - name: Create Tunnel (expose port 5900 for VNC)
      run: ./ngrok tcp 5900
