name: Cl

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: macos-12

    steps:
    - name: Download ngrok
      run: curl -fsSL https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-darwin-amd64.zip -o ngrok.zip
    - name: Extract ngrok
      run: unzip ngrok.zip
    - name: Auth (using encrypted secret)
      run: ./ngrok authtoken ${{ secrets.NGROK_AUTH_TOKEN }}
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
    - name: Install expect
      run: brew install expect
    - name: Change user password
      run: |
        expect << EOF
        spawn passwd runner
        expect "New password:"
        send "P@ssw0rd!\r"
        expect "Retype new password:"
        send "P@ssw0rd!\r"
        expect eof
        EOF
    - name: Enable Screen Sharing
      run: |
        sudo /System/Library/CoreServices/RemoteManagement/ARDAgent.app/Contents/Resources/kickstart -activate -configure -access -on -privs -all -restart -agent -menu
        sudo /System/Library/CoreServices/RemoteManagement/ARDAgent.app/Contents/Resources/kickstart -configure -users runner -access -on -privs -all
    - name: Set VNC password
      run: |
        echo "P@ssw0rd!" | sudo tee /Library/Preferences/com.apple.VNCSettings.txt
        sudo /System/Library/CoreServices/RemoteManagement/ARDAgent.app/Contents/Resources/kickstart -configure -clientopts -setvnclegacy -vnclegacy yes
        sudo /System/Library/CoreServices/RemoteManagement/ARDAgent.app/Contents/Resources/kickstart -configure -clientopts -setvncpw -vncpw P@ssw0rd!
    - name: Create Tunnel (expose port 5900 for VNC)
      run: ./ngrok tcp 5900
