name: Cl

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: macos-12

    steps:
    - name: Download ngrok
      run: curl -fsSL https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-darwin-amd64.zip -o ngrok.zip
    - name: Extract ngrok
      run: unzip ngrok.zip
    - name: Auth (using encrypted secret)
      run: ./ngrok authtoken ${{ secrets.NGROK_AUTH_TOKEN }}
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
    - name: Install Homebrew
      run: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
    - name: Add Homebrew to PATH
      shell: bash
      run: |
        echo 'eval "$(/usr/local/bin/brew shellenv)"' >> $HOME/.bash_profile
        source $HOME/.bash_profile
        echo 'eval "$(/usr/local/bin/brew shellenv)"' >> $HOME/.zprofile
        source $HOME/.zprofile
    - name: Install VNC server
      shell: bash
      run: |
        eval "$(/usr/local/bin/brew shellenv)"
        brew install tiger-vnc
    - name: Verify Installation
      shell: bash
      run: which vncpasswd
    - name: Start VNC server
      shell: bash
      run: |
        eval "$(/usr/local/bin/brew shellenv)"
        mkdir -p ~/.vnc
        echo "P@ssw0rd!" | vncpasswd -f > ~/.vnc/passwd
        chmod 600 ~/.vnc/passwd
        vncserver :1 -geometry 1280x800 -depth 24
    - name: Create Tunnel (expose port 5901 for VNC)
      run: ./ngrok tcp 5901
